### ISSUE TITLE
Not possible to install kvm

### ISSUE THREAD

**Issue by Ruffio** [lluppes/pisharp#3]
When running 5_install_kvm I get an error:

pi@raspberrypi ~ $ sh 5_install_kvm
Cloning into 'home'...
remote: Counting objects: 1142, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 1142 (delta 1), reused 0 (delta 0), pack-reused 1135
Receiving objects: 100% (1142/1142), 703.15 KiB | 633 KiB/s, done.
Resolving deltas: 100% (662/662), done.
sh: 0: Can't open /home/pi/sources/aspnet5/home/kvminstall.sh
  Run this command:      source /home/pi/.k/kvm/kvm.sh
  Then run this command: kvm upgrade
pi@raspberrypi ~ $ source /home/pi/.k/kvm/kvm.sh
-bash: /home/pi/.k/kvm/kvm.sh: No such file or directory
pi@raspberrypi ~ $

**Comment by nutkracker** [comment]
kvm has been replaced.
you will need to:

sh ~/sources/aspnet5/home/dnvminstall.sh
source /home/pi/.dnx/dnvm/dnvm.sh
dmvm upgrade
